[loadbalancers]
lb1 ansible_host=192.168.44.11 ansible_ssh_private_key_file=~/.ssh/vagrant_keys/lb1_key
lb2 ansible_host=192.168.44.12 ansible_ssh_private_key_file=~/.ssh/vagrant_keys/lb2_key

[webservers]
web1 ansible_host=192.168.44.21 ansible_ssh_private_key_file=~/.ssh/vagrant_keys/web1_key
web2 ansible_host=192.168.44.22 ansible_ssh_private_key_file=~/.ssh/vagrant_keys/web2_key

[databases]
db1 ansible_host=192.168.44.31 ansible_ssh_private_key_file=~/.ssh/vagrant_keys/db1_key
db2 ansible_host=192.168.44.32 ansible_ssh_private_key_file=~/.ssh/vagrant_keys/db2_key

[storage]
storage1 ansible_host=192.168.44.41 ansible_ssh_private_key_file=~/.ssh/vagrant_keys/storage1_key

[redis_cluster]
storage1 ansible_host=192.168.44.41 ansible_ssh_private_key_file=~/.ssh/vagrant_keys/storage1_key
storage2 ansible_host=192.168.44.42 ansible_ssh_private_key_file=~/.ssh/vagrant_keys/storage2_key
storage3 ansible_host=192.168.44.43 ansible_ssh_private_key_file=~/.ssh/vagrant_keys/storage3_key

[minio]
minio1 ansible_host=192.168.44.51 ansible_ssh_private_key_file=~/.ssh/vagrant_keys/minio1_key

[monitoring]
monitor1 ansible_host=192.168.44.61 ansible_ssh_private_key_file=~/.ssh/vagrant_keys/monitor1_key

[all:vars]
ansible_user=vagrant
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
