- name: Provisionamento Reativo do Docker Swarm Multi-Região
  hosts: all
  become: yes
  tasks:
    - name: Instalar dependencias e Docker
      apt:
        name: [curl, apt-transport-https, ca-certificates]
        state: present
        update_cache: yes

    - name: Instalar Docker oficial
      shell: curl -fsSL https://get.docker.com | sh
      args:
        creates: /usr/bin/docker

    - name: Bloco do Manager
      when: role == 'manager'
      block:
        - name: Inicializar Swarm
          command: docker swarm init --advertise-addr {{ local_ip }} --listen-addr 0.0.0.0:2377
          when: role == 'manager'

        - name: Obter tokens
          command: docker swarm join-token {{ item }} -q
          loop: [worker, manager]
          register: tokens
        
        - name: Gravar Estado na API
          uri:
            url: "http://{{ orchestrator_ip }}:5000/api/cluster/state"
            method: PUT
            body_format: json
            body: 
              manager_ip: "{{ local_ip }}"
              swarm_port: "{{ swarm_port }}"
              worker_token: "{{ tokens.results[0].stdout }}"
              manager_token: "{{ tokens.results[1].stdout }}"

    - name: Bloco do Worker
      when: role == 'worker'
      block:
        - name: Aguardar Token
          uri:
            url: "http://{{ orchestrator_ip }}:5000/api/cluster/state"
            method: GET
            return_content: yes
          register: state
          until: "state.json.worker_token is defined"
          retries: 20
          delay: 5

        - name: Juntar ao Cluster
          command: "docker swarm join --token {{ state.json.worker_token }} {{ manager_ip }}:{{ state.json.swarm_port }}"