Vagrant.configure("2") do |config|
  node_id = ENV['MC_NODE_ID'] || "0"
  role = ENV['NODE_ROLE'] || "worker"
  manager_ip = ENV['MANAGER_API_IP'] || "127.0.0.1"
  local_ip = ENV['LOCAL_TAILSCALE_IP'] || "127.0.0.1"
  swarm_token = ENV['SWARM_TOKEN'] || ""
  
  # Calculamos a porta baseada no ID para evitar colisões
  swarm_port   = (2377 + node_id.to_i)
  gossip_port  = (7946 + node_id.to_i)
  overlay_port = (4789 + node_id.to_i)

  config.vm.define "swarm-node-#{node_id}" do |node|
    node.vm.box = `uname -m`.strip == 'x86_64' ? "ubuntu/jammy64" : "bento/ubuntu-22.04"
    node.vm.hostname = "swarm-node-#{node_id}"

    node.vm.network "forwarded_port", guest: 2377, host: swarm_port, host_ip: "0.0.0.0", id: "swarm_mgmt"
    node.vm.network "forwarded_port", guest: 7946, host: gossip_port, host_ip: "0.0.0.0", id: "swarm_gossip_tcp"
    node.vm.network "forwarded_port", guest: 7946, host: gossip_port, host_ip: "0.0.0.0", protocol: "udp", id: "swarm_gossip_udp"
    node.vm.network "forwarded_port", guest: 4789, host: overlay_port, host_ip: "0.0.0.0", protocol: "udp", id: "swarm_overlay"

    node.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "swarm-node-#{node_id}"
    end

    node.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "provision.yml"
      ansible.extra_vars = {
          "role"            => role,
          "local_ip"        => local_ip,
          "orchestrator_ip" => local_ip,
          "manager_ip"      => manager_ip,
          "token"           => swarm_token,
          "swarm_port"      => swarm_port
      }
    end
  end
end